# Uncomment this file to enable multilanguage site support

[zh-tw]
languageName = "繁體中文"
languagedirection = "ltr"
title = "edisonlee55's Blog"
weight = 1

[en]
languageName = "English"
languagedirection = "ltr"
title = "edisonlee55's Blog"
weight = 2
